version: '3.9'

services:
  bank:
    image: bank:0.0.1
    build: .
    ports:
      - "8000:8000"

  mysql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'sample_bank'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3305:3307"
       
