# Generated by Django 5.0.2 on 2024-02-22 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardapplication",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(2034, 2, 20, 0, 28, 40, 240002)
            ),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="issue_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
