# Generated by Django 5.0.2 on 2024-04-15 14:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_remove_cardapplication_card_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CardApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(default=datetime.datetime.now)),
                (
                    "expiry_date",
                    models.DateField(
                        default=datetime.datetime(2024, 4, 15, 20, 29, 17, 696340)
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.cardtype"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CardRequest",),
    ]
