# Generated by Django 5.0.2 on 2024-04-15 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_cardtype_cardapplication_delete_cardrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="cardtype", name="name",),
        migrations.AddField(
            model_name="cardtype",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("master", "MasterCard"),
                    ("credit", "Credit Card"),
                    ("debit", "Debit Card"),
                ],
                default="master",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 20, 41, 57, 275794)
            ),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="issue_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 20, 41, 57, 275794)
            ),
        ),
    ]
