# Generated by Django 5.0.2 on 2024-04-15 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_remove_cardtype_name_cardtype_card_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cardtype", name="card_type",),
        migrations.AddField(
            model_name="cardtype",
            name="name",
            field=models.CharField(default="master", max_length=100),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 21, 18, 48, 401704)
            ),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="issue_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 21, 18, 48, 401704)
            ),
        ),
    ]
