# Generated by Django 5.0.2 on 2024-04-15 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0015_alter_cardapplication_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardapplication",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 21, 37, 14, 134124)
            ),
        ),
        migrations.AlterField(
            model_name="cardapplication",
            name="issue_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 15, 21, 37, 14, 134124)
            ),
        ),
    ]
