# Generated by Django 5.0.2 on 2024-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdocument",
            name="document_name",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
