# Generated by Django 5.0.2 on 2024-02-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdocument",
            name="account_number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
