# Generated by Django 5.0.2 on 2024-02-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_kycdocument_account_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="kycdocument", name="account_number",),
    ]
